version: '3.9'

services:

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.13
    ports:
      - 80:8080
    volumes:
      - ./os-base/nginx-base:/oxpoapi
    environment:
      SWAGGER_JSON: /oxpoapi/oxpoapi.json
      DEFAULT_TOPOLOGY: ${DEFAULT_TOPOLOGY}
      DEFAULT_CONNECTION: ${DEFAULT_CONNECTION}
      DEFAULT_URL: ${DEFAULT_URL}
      TOPOLOGY_PATH: ${TOPOLOGY_PATH}
      CONNECTION_PATH: ${CONNECTION_PATH}
      TOPOLOGY_1: ${TOPOLOGY_1}
      TOPOLOGY_2: ${TOPOLOGY_2}
      TOPOLOGY_3: ${TOPOLOGY_3}
      CONNECTION_1: ${CONNECTION_1}
      CONNECTION_2: ${CONNECTION_2}
      CONNECTION_3: ${CONNECTION_3}
      URL_1: ${URL_1}
      URL_2: ${URL_2}
      URL_3: ${URL_3}


  topology-conversion:
    container_name: topology-conversion
    image: topology-conversion
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.15
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: [ "python3", "-m", "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8000" ]

networks:
  kytos_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  persistent:
